apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mmwcnd5qg-nodejs 
  janus-idp.io/tekton: mmwcnd5qg-nodejs
  backstage.io/kubernetes-id: mmwcnd5qg-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mmwcnd5qg-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  